[mypy]
mypy_path = typings
python_version = 3.12
exclude = (?x)(^\.venv\\|^\.mypy_cache\\|^\.pytest_cache\\|__pycache__)

[mypy-colorama]
ignore_missing_imports = True

[mypy-colorama.*]
ignore_missing_imports = True

[mypy-requests]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True

[mypy-psutil]
ignore_missing_imports = True

[mypy-psutil.*]
ignore_missing_imports = True
