(
    WAIT_REG_NIP, WAIT_REG_PASS, WAIT_REG_NAME, WAIT_REG_UPT,
    WAIT_MAN_NIP, WAIT_MAN_PASS, WAIT_MAN_ACTION,
    WAIT_SET_IN, WAIT_SET_OUT, WAIT_SET_DAYS, WAIT_SET_LOC,
    WAIT_ADMIN_INPUT_VAL, WAIT_ADMIN_CONFIRM_DEL,
    WAIT_SEARCH_QUERY, WAIT_BROADCAST_MSG,
    WAIT_ADMIN_ADD_NIP, WAIT_ADMIN_ADD_PASS, WAIT_ADMIN_ADD_NAME, WAIT_ADMIN_ADD_UPT,
    WAIT_ADMIN_ADD_SCHEDULE, WAIT_ADMIN_ADD_WORKDAYS, WAIT_ADMIN_ADD_LOC
) = range(22)
